<?
$PERM["admin"]["13"]="T_8";
$PERM["admin"]["10"]="T_8";
$PERM["admin"]["9"]="T_8";
$PERM["admin"]["7"]="T_8";
$PERM["admin"]["6"]="T_8";
$PERM["admin"]["*"]="D";
$PERM["tools"]["5"]="T_8";
$PERM["wizards"]["*"]="D";
$PERM["routing_index.php"]["2"]="R";
?>